#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail
FRAGMENTS_DIR="@FRAGMENTS_DIR@"
ASSEMBLE_SCRIPT="@ASSEMBLE_SCRIPT@"
DETECT_SCRIPT="@DETECT_SCRIPT@"
SETTING_SRC="@SETTING_SRC@"
CONFIRM_SCRIPT="@CONFIRM_SCRIPT@"
CONFIRM_REV="@CONFIRM_REV@"
export FRAGMENTS_DIR ASSEMBLE_SCRIPT DETECT_SCRIPT SETTING_SRC CONFIRM_SCRIPT CONFIRM_REV
bash "$CONFIRM_SCRIPT"
